buckets:
  dev:
    cert_name: "file_dev.jks"
    key_store_password: "1234"
    public_key_password: "1234"
    private_key_password: "1234"
    public_key_alias: "alias-public"
    private_key_alias: "alias-private"

  cer:
    cert_name: "file_cer.jks"
    key_store_password: "1234"
    public_key_password: "1234"
    private_key_password: "1234"
    public_key_alias: "alias-public"
    private_key_alias: "alias-private"
